---
- hosts: authserver1
  become: true
  roles:
    - superLoginSetupServer
    - role: superLoginCloneRepoDocker
      tags: [update, clone]
    - role: superLoginDockerCompose
      tags: update
    - role: superLoginDockerNginx
      tags: update
    - role: superLoginDockerCertbot
      tags: [update, certbot]
