#####
###  CLONE REPO
#
---
- debug:
    msg: START CLONE REPO...

- name: git - pull or clone {{REPOSITORY}}
  become: true
  shell: '[ -d "./{{REPO_NAME}}" ] && (cd "./{{REPO_NAME}}" && git fetch origin) || (git clone {{REPOSITORY}} && cd "./{{REPO_NAME}}" && git fetch origin)'
  register: result
- name: debug [git - pull or clone {{REPOSITORY}}]
  debug:
    var: result

- name: git - checkout {{BRANCH_NAME}}
  become: true
  shell: 'cd "./{{REPO_NAME}}" && git checkout {{BRANCH_NAME}} && git pull origin {{BRANCH_NAME}}'
  register: result
- name: debug [git - checkout {{BRANCH_NAME}}]
  debug:
    var: result

- name: copy files local to remote with a template (.env)
  template:
    src: env
    dest: ./{{REPO_NAME}}/.env
  register: result
- name: debug [copy files local to remote with a template (.env)]
  debug:
    var: result

- name: copy files local to remote with a template (Dockerfile)
  template:
    src: Dockerfile
    dest: ./{{REPO_NAME}}/Dockerfile
  register: result
- name: debug [copy files local to remote with a template (Dockerfile)]
  debug:
    var: result

- debug:
    msg: END CLONE REPO...
