#####
###  DOCKER COUCHDB
#
---
- debug:
    msg: START DOCKER COUCHDB...

- name: create folder ./couchdb/conf/
  file:
    path: ./couchdb/conf/local.d
    state: directory
  register: result
- name: debug [create folder ./couchdb/conf/]
  debug:
    var: result

- name: copy files local to remote (100-couchdb.conf)
  template:
    src: 100-couchdb-conf
    dest: /etc/security/limits.d/100-couchdb.conf
  register: result
- name: debug [copy files local to remote with a template (100-couchdb.conf)]
  debug:
    var: result

- name: copy files local to remote with a template (Dockerfile)
  template:
    src: Dockerfile
    dest: ./Dockerfile
  register: result
- name: debug [copy files local to remote with a template (Dockerfile)]
  debug:
    var: result

- name: copy files local to remote with a template (local-ini)
  template:
    src: local-ini
    dest: ./couchdb/conf/local.ini
  register: result
- name: debug [copy files local to remote with a template (local-ini)]
  debug:
    var: result

- name: copy files local to remote with a template (local-d-ini)
  template:
    src: local-d-ini
    dest: ./couchdb/conf/local.d/docker.ini
  register: result
- name: debug [copy files local to remote with a template (local-d-ini)]
  debug:
    var: result

- name: copy files local to remote (vm.args)
  template:
    src: vm-args
    dest: ./couchdb/conf/vm.args
  register: result
- name: debug [copy files local to remote with a template (vm.args)]
  debug:
    var: result

- name: copy files local to remote (100-couchdb.conf)
  template:
    src: 100-couchdb-conf
    dest: ./couchdb/conf/100-couchdb.conf
  register: result
- name: debug [copy files local to remote with a template (100-couchdb.conf)]
  debug:
    var: result

- debug:
    msg: END DOCKER COUCHDB...